name: Build MD to PDF and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Pandoc + LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base

      - name: Convert Markdown to PDF
        run: |
          mkdir -p output
          for file in *.md; do
            [ -e "$file" ] || continue
            pandoc "$file" -o "output/${file%.md}.pdf"
          done

      - name: Init gh-pages branch
        run: |
          mkdir gh-pages
          cp -r output/* gh-pages/

      - name: Deploy to gh-pages
        run: |
          cd gh-pages
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b gh-pages
          git add .
          git commit -m "Update PDFs" || echo "No changes"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
